### ISSUE TITLE
Is this for Firestore only, or also Realtime Database?

### ISSUE THREAD

**Issue by BobDankert** [transistorsoft/cordova-background-geolocation-firebase#1]
The documentation/readme makes this appear to be for Cloud Firestore only, though I don't see it explicitly stated one way or another. We've been hesitant to migrate to Firestore since it is still technically a Beta product, and doesn't seem appropriate for production purposes yet, so we are still on Realtime Database. 

If this is for Cloud Firestore only, are there plans to make a similar module/package or extend support for Realtime Database?

**Comment by christocracy** [comment]
Yes, it's Firestore only currently.  It could probably be tweaked to support whatever Firebase storage mechanism you desire.

**Comment by BobDankert** [comment]
Got it. I'd be interested to know if you add Realtime Database support in the future. I can submit a new issue for that feature request, if you'd like :)
