### ISSUE TITLE
Add support for firebase.firestore.FieldValue.serverTimestamp()

### ISSUE THREAD

**Issue by vincentdsf** [transistorsoft/cordova-background-geolocation-firebase#15]
## Your Environment
* Plugin version: 0.1.0
* Platform: iOS 
* OS version: iOS13
* Device manufacturer / model: emulator
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): 
Installed platforms:
  ios 5.1.1
Available platforms: 
  android ^8.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
My App starts with ready on App start with reset:true and configures Plugin after receiving additional information that need to be stored with the Position.
Ready:
BackgroundGeolocation.ready({
			reset: true,
			disableLocationAuthorizationAlert: true
		}
Config:
BackgroundGeolocation.setConfig({
			// Logging / Debug config
			debug: false, //  enable this hear sounds for background-geolocation life-cycle.
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			// Geolocation config
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, // Desired accuracy in meters.
			triggerActivities: "in_vehicle",
			disableElasticity: true, // To make sure one App-User only creates a max. amount of position we can specify per day
			distanceFilter: 1000,
			fastestLocationUpdateInterval: 5 * 60 * 1000,
			disableLocationAuthorizationAlert: true,
			geofenceProximityRadius: 500,
			// Application config
			disableStopDetection: true,
			pausesLocationUpdatesAutomatically: false,
			stopOnTerminate: false,
			startOnBoot: true,
			foregroundService: true,
			enableTimestampMeta: true,
			reset: true, //  If you wish to force the #ready method to always apply the supplied config {}, you can specify reset: true
			notification: {
				title: 'Tracking aktiviert!',
				text: 'GPS Hintergrundtracking wurde aktiviert.'
			},
			params: {
				some params..
                                 firestoreTimestamp: firebase.firestore.FieldValue.serverTimestamp()
		},
```

## Expected Behavior
When trying to pass in params as parameter
firestoreTimestamp: firebase.firestore.FieldValue.serverTimestamp() 
I want the Position-Doc to be successfully stored in Firstore with the Serverside Timestamp.

## Actual Behavior
The following error comes and positions dont get stored in Firestore:
WARN: - BackgroundGeolocation configuration error:  TypeError: JSON.stringify cannot serialize cyclic structures.

## Steps to Reproduce

1. Add a parameter or extra field with value firebase.firestore.FieldValue.serverTimestamp() or FieldValue.serverTimestamp() 

## Context
I want Firestore Documents created by Background Plugin to have a timestamp created on server-side. If the user changes the phones time settings, the positions become invalid if an application depends on the correct timestamp.

## Debug logs
WARN: - BackgroundGeolocation configuration error:  TypeError: JSON.stringify cannot serialize cyclic structures.
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

Anything else I can do to achieve my goal or is this something that needs to be implemented?

**Comment by vincentdsf** [comment]
Updated Issue with more information

**Comment by christocracy** [comment]
You can't do what you're attempting to do.

Use [Firebase Functions](https://firebase.google.com/docs/functions/?gclid=CjwKCAjwjLD4BRAiEiwAg5NBFvOk0NKJKDr6c89haWX6H2GbpuZxjlgACezsGklH2zoQVJn8o2RmARoCR_gQAvD_BwE) to set server timestamp.
