### ISSUE TITLE
Can I use this plugin for getting push notification

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-firebase#18]
## Your Environment
* Plugin version:4.0.1
* Platform: iOS or Android : IOS
* OS version: 5.1.1
* Device manufacturer / model:
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): 6.2.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
I need to send push notification using this plugin

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
This is a location-tracking plugin.  It has nothing at all to do with push notifications.

Use a 3rd party library specializing in push notifications.
