### ISSUE TITLE
cordova build failing on firebase and play-services dependencies

### ISSUE THREAD

**Issue by invention7** [transistorsoft/cordova-background-geolocation-firebase#3]
Hi Chris,

I know from the main repository's issues that play-services versioning tends to be the bane of your existence.   Hoping you've got an immediate idea, if not, I'll continue tinkering.

I can build fine with cordova-background-geolocation (I've hosed platforms/ and plugin/ rebuilt the android platform and works fine).  Once I add  cordova-background-geolocation-firebase and do an android build, I fail with :

What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[15.0.4,15.0.4], [16.0.2,16.0.2]], but resolves to 16.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics-impl is being requested by various other libraries at [[16.0.0,16.0.0], [16.2.1,16.2.1]], but resolves to 16.2.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

Pasting below my templated config.xml  (I use a project called 'ionic-config' to fill in variables per my 'dev', 'staging', and 'prod' platforms)

Any ideas are appreciated.

Thanks for the help.

<?xml version='1.0' encoding='utf-8'?>
<widget id="{{id}}" version="0.3.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <hook src="ionic-configurator/hooks.js" type="before_plugin_add" />
    <hook src="ionic-configurator/hooks.js" type="after_plugin_add" />
    <hook src="ionic-configurator/hooks.js" type="before_plugin_rm" />
    <hook src="ionic-configurator/hooks.js" type="after_plugin_rm" />
    <name>{{name}}</name>
    <author email="seth@ryplz.com" href="http://ryplz.com/">Ryplz, LLC</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-navigation href="http://ionic.local/*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="23" />
    <preference name="BackupWebStorage" value="none" />
    <platform name="android">
        <hook src="{{license_hook}}" type="after_prepare" />
        <allow-intent href="market:*" />
        <config-file parent="/resources" target="./res/values/strings.xml">
            <string name="fb_app_id">1597726337191073</string>
            <string name="fb_app_name">Air Castle</string>
        </config-file>
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <allow-navigation href="http://192.168.1.10:8100" />
    <allow-navigation href="http://192.168.1.3:8100" />
    <allow-navigation href="http://192.168.1.3:8101" />
    <allow-navigation href="http://192.168.1.149:8101" />
    <allow-navigation href="http://192.168.1.149:8100" />
    <allow-navigation href="http://10.234.160.104:8100" />
    <allow-navigation href="http://192.168.1.6:8100" />
    <allow-navigation href="http://192.168.1.6:8100" />
    <allow-navigation href="http://192.168.1.9:8100" />
    <allow-navigation href="http://localhost:8080/*" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <allow-navigation href="http://192.168.1.6:8101" />
    <allow-navigation href="http://10.227.96.136:8100" />
    <allow-navigation href="http://192.168.1.11:8100" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreenDelay" value="10000" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="FadeSplashScreenDuration" value="2000" />
    <preference name="FadeSplashScreen" value="true" />
    <preference name="SplashScreenBackgroundColor" value="#3ebffb" />
    <allow-navigation href="http://192.168.1.7:8100" />
    <engine name="ios" spec="4.5.4" />
    <engine name="android" spec="7.1.1" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-badge" spec="^0.8.7" />
    <plugin name="cordova-plugin-firebase" spec="^1.0.5" />
    <plugin name="cordova-plugin-local-notification" spec="^0.9.0-beta.2" />
    <plugin name="cordova-plugin-background-fetch" spec="^5.4.1" />
    <plugin name="cordova-plugin-ionic-webview" spec="^2.1.4">
        <variable name="ANDROID_SUPPORT_ANNOTATIONS_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-buildinfo" spec="^1.1.0" />
    <plugin name="cordova-plugin-camera" spec="^4.0.3">
        <variable name="CAMERA_USAGE_DESCRIPTION" value=" " />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-sqlite-storage" spec="^2.4.0" />
    <plugin name="com-sarriaroman-photoviewer" spec="^1.1.18" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-app-version" spec="^0.1.9" />
    <plugin name="cordova-plugin-ionic" spec="^5.2.4">
        <variable name="APP_ID" value="REDACTED" />
        <variable name="CHANNEL_NAME" value="Development" />
        <variable name="UPDATE_METHOD" value="auto" />
        <variable name="WARN_DEBUG" value="false" />
        <variable name="UPDATE_API" value="https://api.ionicjs.com" />
        <variable name="MAX_STORE" value="2" />
        <variable name="MIN_BACKGROUND_DURATION" value="30" />
    </plugin>
    <plugin name="cordova-background-geolocation" spec="git+https://640d7a9a16168acd26ad4faa851a1d56d5e71ad7:x-oauth-basic@github.com/invention7/cordova-background-geolocation.git">
        <variable name="LICENSE" value="REDACTED" />
        <variable name="GOOGLE_API_VERSION" value="15.0.1" />
        <variable name="APPCOMPAT_VERSION" value="27.0.0" />
        <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Always use is required for background location tracking" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>
    <plugin name="cordova-plugin-facebook4" spec="^3.0.0">
        <variable name="APP_ID" value="REDACTED" />
        <variable name="APP_NAME" value="Air Castle" />
        <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="4.36.0" />
    </plugin>
    <plugin name="cordova-background-geolocation-firebase" spec="0.0.1">
        <variable name="LICENSE" value="YOUR_LICENSE_KEY" />
        <variable name="FIREBASE_CORE_VERSION" value="16.0.1" />
        <variable name="FIREBASE_FIRESTORE_VERSION" value="17.1.0" />
    </plugin>
</widget>

**Comment by christocracy** [comment]
post your `platforms/android/project.properties`

**Comment by invention7** [comment]
`
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=com-sarriaroman-photoviewer/dev-photoviewer.gradle
cordova.gradle.include.2=cordova-plugin-background-fetch/dev-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation/dev-build.gradle
cordova.gradle.include.4=cordova-plugin-badge/dev-badge.gradle
cordova.system.library.3=com.android.support:support-v4:24.1.1+
cordova.system.library.4=com.facebook.android:facebook-android-sdk:4.36.0
cordova.gradle.include.5=cordova-plugin-firebase/dev-build.gradle
cordova.system.library.5=com.google.gms:google-services:+
cordova.system.library.6=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.7=com.google.firebase:firebase-core:+
cordova.system.library.8=com.google.firebase:firebase-messaging:+
cordova.system.library.9=com.google.firebase:firebase-crash:+
cordova.system.library.10=com.google.firebase:firebase-config:+
cordova.system.library.11=com.google.firebase:firebase-perf:+
cordova.system.library.12=com.android.support:support-annotations:27.+
cordova.system.library.13=com.android.support:support-v4:26.+
cordova.gradle.include.6=cordova-plugin-local-notification/dev-localnotification.gradle
cordova.gradle.include.7=cordova-support-google-services/dev-build.gradle
cordova.system.library.14=com.google.firebase:firebase-core:15.0.0
cordova.system.library.15=com.google.firebase:firebase-firestore:15.0.0
cordova.gradle.include.8=cordova-background-geolocation-firebase/dev-build.gradle`

**Comment by christocracy** [comment]
Your dependencies are a mess of conflicting versions.

**Comment by invention7** [comment]
ok.

I just reverted to my working code (pre  cordova-background-geolocation-firebase install).  Axed plugins/ and platforms/   Did a clean add of android platform and built successfully.

Posting the resulting project.properties below.
Does this offer you any opportunity for insight into what is causing the mess of conflicting versions?

(in other words, the project.properties below builds; when I add the plugin, I get the project.properties above.  Can you glean any area to focus my investigation?)

`
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=com-sarriaroman-photoviewer/dev-photoviewer.gradle
cordova.gradle.include.2=cordova-plugin-background-fetch/dev-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation/dev-build.gradle
cordova.gradle.include.4=cordova-plugin-badge/dev-badge.gradle
cordova.system.library.3=com.android.support:support-v4:24.1.1+
cordova.system.library.4=com.facebook.android:facebook-android-sdk:4.36.0
cordova.gradle.include.5=cordova-plugin-firebase/dev-build.gradle
cordova.system.library.5=com.google.gms:google-services:+
cordova.system.library.6=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.7=com.google.firebase:firebase-core:+
cordova.system.library.8=com.google.firebase:firebase-messaging:+
cordova.system.library.9=com.google.firebase:firebase-crash:+
cordova.system.library.10=com.google.firebase:firebase-config:+
cordova.system.library.11=com.google.firebase:firebase-perf:+
cordova.system.library.12=com.android.support:support-annotations:27.+
cordova.system.library.13=com.android.support:support-v4:26.+
cordova.gradle.include.6=cordova-plugin-local-notification/dev-localnotification.gradle`

**Comment by christocracy** [comment]
for one thing, all `com.android.support` dependencies should be aligned and correspond to your `target=android-27`.

```
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0 
cordova.system.library.3=com.android.support:support-v4:24.1.1+ 
cordova.system.library.12=com.android.support:support-annotations:27.+ 
cordova.system.library.13=com.android.support:support-v4:26.+ 
```

- Seeing dependencies requesting version with `+` is always suspicious.

**Comment by invention7** [comment]
I know on the regular cordova-background-geolocation issues, I've seen some success using plugins like cordova-android-play-services-gradle-release and cordova-android-firebase-gradle-release to align versions.  Do you think using some combinations of plugins is a viable route, or do you think the choice is really to manually align the versions in project.properties?  (and maybe codifying in a cordova hook to make a repeatable process?)

**Comment by christocracy** [comment]
make it build by manually tweaking first.

**Comment by invention7** [comment]
I'll give it a go and get back to you.  Thanks, Chris.

**Comment by invention7** [comment]
Thanks for the guidance, Chris.  Got it building and codified the explicit versions in a build-extras.gradle which I've got coming in to platforms/android via a hook.  Closing

**Comment by syedsaadqamar** [comment]
@christocracy I had the same issue but I had changed it by changing 
```
cordova.system.library.1=com.google.android.gms:play-services-location:16.+
```
to 
```
cordova.system.library.1=com.google.android.gms:play-services-location:15.+
```
 in `platforms/android/project.properties`

Locally that works but when I push the code on `dashboard.ionicframework` and build the app it fails there because we don't push the `platform` folder in `dashboard.ionicframework`, could you please help me what should I do to resolve that issue?

**Comment by christocracy** [comment]
See the README for GOOGLE_API_VERSION

**Comment by syedsaadqamar** [comment]
Installed `GOOGLE_API_VERSION=15.+` but it does not work

**Comment by christocracy** [comment]
Logs.

**Comment by syedsaadqamar** [comment]
How can get logs?

**Comment by syedsaadqamar** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

**Comment by syedsaadqamar** [comment]
Installed plugin

```
"cordova-background-geolocation-firebase": "0.0.1",
"cordova-support-google-services": "^1.2.1",
"cordova": {
    "plugins": {
      "cordova-background-geolocation": {
        "GOOGLE_API_VERSION": "15.+",
        "APPCOMPAT_VERSION": "27.1.1",
        "BACKGROUND_MODE_LOCATION": "<string>location</string>",
        "LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION": "Always use is required for constant background location-tracking",
        "LOCATION_ALWAYS_USAGE_DESCRIPTION": "Background location-tracking is required",
        "LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION": "Background location-tracking is required",
        "MOTION_USAGE_DESCRIPTION": "Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving"
      },
      "cordova-support-google-services": {},
      "cordova-background-geolocation-firebase": {
        "LICENSE": "",
        "FIREBASE_CORE_VERSION": "15.+",
        "FIREBASE_FIRESTORE_VERSION": "17.1.0"
      }
}
```

**Comment by christocracy** [comment]
I need to document [these two `--variable`](https://github.com/transistorsoft/cordova-background-geolocation-firebase/blob/master/plugin.xml#L48-L52) of the firebase adapter.
- `FIREBASE_CORE_VERSION`
- `FIREBASE_FIRESTORE_VERSION`

I would start by making sure all the Google dependencies are importing latest versions.  You can determine latest versions by browsing the tree @  http://maven.google.com

- `GOOGLE_API_VERSION` (this is for `play-services-location` of background-geolocation):  16.0.0
- `FIREBASE_CORE_VERSION: 16.0.9`
- `FIREBASE_FIRESTORE_VERSION: 19.0.0`

Test on your local build first.  Ensure your `project.properties` reflects these updated versions.

**Comment by christocracy** [comment]
I probably need to update the [cordova-support-google-services](https://github.com/transistorsoft/cordova-background-geolocation-firebase/blob/master/plugin.xml#L24) dependency as well, which is at `1.3.1` now.

It's been a while since I've tested the firebase adapter for Cordova.  I'll whip up a Hello World on Monday using latest dependencies.

**Comment by syedsaadqamar** [comment]
Thanks @christocracy, It works!

**Comment by Syed-Saad-Qamar** [comment]
The build was a success but the `bgGeoFirebase.configure` was not working
