### ISSUE TITLE
Nothing is logged on DEBUG build

### ISSUE THREAD

**Issue by markokhman** [transistorsoft/cordova-background-geolocation-firebase#6]
Platform: Android
Plugins versions:
cordova-background-geolocation-lt 3.0.0 "BackgroundGeolocation"
cordova-background-geolocation-firebase 0.0.1 "CDVBackgroundGeolocationFirebase"

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 13 other plugins)

Im running on a debug build without a license
Getting no logs on configure
Noting is recorded to the collections i set on configure
Getting "License failed" notice on app launch - i guess this plugin is supposed to work without license on debug builds?

What could that be?

**Comment by christocracy** [comment]
```javascript
BackgroundGeolocation.ready({
  reset: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  .
  .
  .
});
```

**Comment by christocracy** [comment]
Closed for lack of feedback.
