### ISSUE TITLE
Build Failed 

### ISSUE THREAD

**Issue by lnegi52** [transistorsoft/cordova-background-geolocation-firebase#8]
BUILD FAILED in 5s
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: /Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:3: error: package com.transistorsoft.locationmanager.logger does not exist
import com.transistorsoft.locationmanager.logger.TSLog;
                                                ^
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:29: error: cannot find symbol
        TSLog.logger.info(TSLog.info("[Firebase] $ " + action));
                          ^
  symbol:   variable TSLog
  location: class CDVBackgroundGeolocationFirebase
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:29: error: package TSLog does not exist
        TSLog.logger.info(TSLog.info("[Firebase] $ " + action));
             ^
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:39: error: cannot find symbol
        TSLog.logger.info(TSLog.info("[Firebase] - configure: " + options));
                          ^
  symbol:   variable TSLog
  location: class CDVBackgroundGeolocationFirebase
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:39: error: package TSLog does not exist
        TSLog.logger.info(TSLog.info("[Firebase] - configure: " + options));
             ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by christocracy** [comment]
Did you *read* the issue-template before deleting it?  Closing for ignoring issue template.

![](https://dl.dropbox.com/s/0k8gutpdf0rrug5/Screenshot%202019-07-12%2011.28.29.png?dl=1)

**Comment by christocracy** [comment]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by lnegi52** [comment]
Plugin version:0.1.0
Platform: Android
OS version: Mac Os HighSierra
Device manufacturer / model: Apple/ iMac (21.5-inch, 2017)
Cordova version (cordova -v): 9.0.0
Cordova platform version (cordova platform ls): 8.0.0
Plugin config provided to #ready:



Code: 
ts File:
  ionViewDidLoad() {
    this.platform.ready().then(() => {
      this.configureBackgroundGeolocation();
    });
  }
  configureBackgroundGeolocation() {
    let bgGeoFirebase = (<any>window).BackgroundGeolocationFirebase;

    bgGeoFirebase.configure({
      locationsCollection: "locations",
      geofencesCollection: "geofences"
    });

    let bgGeo = (<any>window).BackgroundGeolocation;

    bgGeo.on("location", location => {
      console.log("[location] - ", location);
    });

    bgGeo.ready(
      {
        stopOnTerminate: false,
        debug: true
      },
      state => {
        if (!state.enabled) {
          bgGeo.start();
        }
      }
    );
  }





Expected Behavior
Actual Behavior
Steps to Reproduce
Context
Debug logs
Logs
> Task :app:createDebugCompatibleScreenManifests
> Task :app:processDebugManifest
> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac FAILED
26 actionable tasks: 26 executed
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:3: error: package com.transistorsoft.locationmanager.logger does not exist
import com.transistorsoft.locationmanager.logger.TSLog;
                                                ^
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:29: error: cannot find symbol
        TSLog.logger.info(TSLog.info("[Firebase] $ " + action));
                          ^
  symbol:   variable TSLog
  location: class CDVBackgroundGeolocationFirebase
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:29: error: package TSLog does not exist
        TSLog.logger.info(TSLog.info("[Firebase] $ " + action));
             ^
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:39: error: cannot find symbol
        TSLog.logger.info(TSLog.info("[Firebase] - configure: " + options));
                          ^
  symbol:   variable TSLog
  location: class CDVBackgroundGeolocationFirebase
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:39: error: package TSLog does not exist
        TSLog.logger.info(TSLog.info("[Firebase] - configure: " + options));
             ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: /Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:3: error: package com.transistorsoft.locationmanager.logger does not exist
import com.transistorsoft.locationmanager.logger.TSLog;
                                                ^
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:29: error: cannot find symbol
        TSLog.logger.info(TSLog.info("[Firebase] $ " + action));
                          ^
  symbol:   variable TSLog
  location: class CDVBackgroundGeolocationFirebase
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:29: error: package TSLog does not exist
        TSLog.logger.info(TSLog.info("[Firebase] $ " + action));
             ^
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:39: error: cannot find symbol
        TSLog.logger.info(TSLog.info("[Firebase] - configure: " + options));
                          ^
  symbol:   variable TSLog
  location: class CDVBackgroundGeolocationFirebase
/Users/webgarhsolutions/Desktop/rohit/backgroundfirebasegeo/platforms/android/app/src/main/java/com/transistorsoft/cordova/bggeo/CDVBackgroundGeolocationFirebase.java:39: error: package TSLog does not exist
        TSLog.logger.info(TSLog.info("[Firebase] - configure: " + options));
             ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build android --device exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by lnegi52** [comment]
cordova-background-geolocation-firebase 0.1.0 "CDVBackgroundGeolocationFirebase"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-google-services 1.3.1 "cordova-support-google-services"

**Comment by christocracy** [comment]
You haven’t installled [`cordova-background-geolocation`](https://github.com/transistorsoft/cordova-background-geolocation)

The Firebase plugin is a *companion plugin for* background Geolocation.
