### ISSUE TITLE
Not saving location on firebase

### ISSUE THREAD

**Issue by lnegi52** [transistorsoft/cordova-background-geolocation-firebase#9]
## Your Environment
* Plugin version: 0.1.0 cordova-background-geolocation-firebase, 3.0.8 cordova-background-geolocation-lt
* Platform: Android
* OS version: Mac Os HighSierra
* Device manufacturer / model:Apple/ iMac (21.5-inch, 2017)
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
configureBackgroundGeolocations() {
    // 1.  Listen to events.
    BackgroundGeolocation.onLocation(location => {
      console.log("[location] - ", location);
    });

    let bgGeo = (<any>window).BackgroundGeolocation;
    BackgroundGeolocation.onMotionChange(event => {
      console.log("[motionchange] - ", event.isMoving, event.location);
      bgGeo.on("location", location => {
        console.log("[location] - ", location);
      });
    });

    BackgroundGeolocation.onHttp(response => {
      console.log(
        "[http] - ",
        response.success,
        response.status,
        response.responseText
      );
    });

    BackgroundGeolocation.onProviderChange(event => {
      console.log(
        "[providerchange] - ",
        event.enabled,
        event.status,
        event.gps
      );
    });

    // 2.  Configure the plugin with #ready
    BackgroundGeolocation.ready(
      {
        reset: true,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        url: "https://my-server/locations",
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true
      },
      state => {
        console.log("[ready] BackgroundGeolocation is ready to use");
        if (!state.enabled) {
          // 3.  Start tracking.
          BackgroundGeolocation.start();
        }
      }
    );
  }
```

## Expected Behavior

 Should save location on firebase
## Actual Behavior

but nothing recorded on firebase
## Context

To save my location on firebase database

**Comment by christocracy** [comment]
Are you watching the plugin logs?

**Comment by lnegi52** [comment]
![Screen Shot 2019-07-15 at 8 39 37 PM](https://user-images.githubusercontent.com/29563327/61226875-e304d100-a740-11e9-995b-12754d98e7e8.png)

**Comment by lnegi52** [comment]
Can it be use with realtime database?

**Comment by christocracy** [comment]
See background-geolocation Wiki [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

**Comment by lnegi52** [comment]
Ok got it i want to know.
Can it be use with realtime database?

**Comment by christocracy** [comment]
>Can it be use with realtime database?

Of course it can

**Comment by lnegi52** [comment]
How can i use it with realtime is there any document for this ?

**Comment by christocracy** [comment]
Have you read the API docs for background-Geolocation?  That’s what you need to start learning about.  

You need to learn to observe the plugin’s Native logs.

**Comment by cWebCo** [comment]
Hi there is no option to get token for push notification in background-Geolocation. if have any method please help ?

**Comment by christocracy** [comment]
Background Geolocation deals with *geolocation*, not push.
